// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcK89FELbFvQlaa6QyP0t80klrxrHJtNs',
    appId: '1:383983416768:web:a86eb03f0d1e8934388425',
    messagingSenderId: '383983416768',
    projectId: 'esport-tournament-app-3266f',
    authDomain: 'esport-tournament-app-3266f.firebaseapp.com',
    storageBucket: 'esport-tournament-app-3266f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvZ7y-1-Getr8kYaG1m3PrZrXnkcPmbbI',
    appId: '1:383983416768:android:174c430657977455388425',
    messagingSenderId: '383983416768',
    projectId: 'esport-tournament-app-3266f',
    storageBucket: 'esport-tournament-app-3266f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBToV0xxgheCfgnZFoL02VUrvUZ3R-ldZE',
    appId: '1:383983416768:ios:5fe5d02cc0145ba5388425',
    messagingSenderId: '383983416768',
    projectId: 'esport-tournament-app-3266f',
    storageBucket: 'esport-tournament-app-3266f.firebasestorage.app',
    iosBundleId: 'com.example.esportTournamentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBToV0xxgheCfgnZFoL02VUrvUZ3R-ldZE',
    appId: '1:383983416768:ios:5fe5d02cc0145ba5388425',
    messagingSenderId: '383983416768',
    projectId: 'esport-tournament-app-3266f',
    storageBucket: 'esport-tournament-app-3266f.firebasestorage.app',
    iosBundleId: 'com.example.esportTournamentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcK89FELbFvQlaa6QyP0t80klrxrHJtNs',
    appId: '1:383983416768:web:92a6216ca986e514388425',
    messagingSenderId: '383983416768',
    projectId: 'esport-tournament-app-3266f',
    authDomain: 'esport-tournament-app-3266f.firebaseapp.com',
    storageBucket: 'esport-tournament-app-3266f.firebasestorage.app',
  );
}
